# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
  Contact: /contact

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/Dread_Boy
github_url: https://github.com/DreadBoy
email_url: contact@vozzel.games
rss_url: \atom.xml

# Footer About Text
footer_about: "Vozzel games is one-man indie game dev studio, formed by Matic Leva."

# Footer Copyright Line
footer_copyright: ""

twitter_handle: "@Dread_Boy"